services:
  thursday-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thursday-core
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file: .env
    environment:
      STT_BASE_URL: http://thursday-stt:9200
      TTS_BASE_URL: http://thursday-tts:9000   
    depends_on:
      - ollama
      - searxng
    volumes:
      - ./brain:/app/brain
    ports:
      - "8000:8000"
  thursday-tts:
    container_name: thursday-tts
    build:
      context: .
      dockerfile: Dockerfile.tts
    volumes:
      - ./out/tts:/app/out/tts
    ports:
      - "9000:9000"
    environment:
      TTS_DEVICE: cuda:0
      TTS_DTYPE: bfloat16
    gpus: all
  thursday-stt:
    container_name: thursday-stt
    build:
      context: .
      dockerfile: Dockerfile.stt
    volumes:
      - ./out/stt:/app/out/stt
    ports:
      - "9200:9200"
    environment:
      STT_DEVICE: cpu
      STT_COMPUTE_TYPE: int8
      STT_MODEL_SIZE: small
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    gpus: all
    ports:
      - "127.0.0.1:11434:11434"
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - BASE_URL=http://localhost:55000/
    ports:
      - "55000:8080"
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
  thursday-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thursday-ui
    restart: unless-stopped
    env_file: .env
    environment:
      STT_BASE_URL: http://thursday-stt:9200
      TTS_BASE_URL: http://thursday-tts:9000
    depends_on:
      - thursday-core
      - thursday-tts
      - thursday-stt
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
volumes:
  ollama: